name: Build push Go app
description: Builds an go app and uploads an artifact

inputs:
  app-path:
    description: Relative path to the folder of the go app.
    type: tring
    required: true

runs:
  using: "composite"
  steps:
  - name: Checkout repository
    uses: actions/checkout@v3

  - name: Set up Go
    uses: actions/setup-go@v4
    with:
      go-version: '1.21'

  - name: Set working directory
    shell: bash
    run: cd ${{ inputs.app-path }}

  - name: Initialize Go module
    shell: bash
    run: |
      go mod init github.com/${{ github.event.repository.name }}/${{ inputs.app-path }}
      go mod tidy

  - name: Build
    run: go build -o ${{ inputs.app-path }} ./${{ inputs.app-path }}

  - name: Archive artifacts
    uses: actions/upload-artifact@v3
    with:
      name: ${{ inputs.app-path }}-artifacts
      path: ${{ inputs.app-path }}