name: Build and Push to GHCR (Helloserver)

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/*'
      - '.github/workflows/composite'
      - 'helloserver/*'
      - 'Dockerfile-helloserver'

jobs:
  update-manifest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    #- name: Build and test go
    #  uses: ./.github/workflows/composite/build-test-go
    #  with:
    #    app-path: helloserver
    
    - name: Upload Dockerfile
      uses: ./.github/workflows/composite/upload-dockerfile-ghcr
      with:
        app-name: helloserver
        ghcr-repo: bf-luca/argo-ghcr-code
        dockerhub-repo: bfminusluca/argo-ghcr-code
        ghcr-user: bf-luca
        PW_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Sync manifest
      uses: ./.github/workflows/composite/sync-manifest
      with:
        app-name: helloserver
        code-repo: bf-luca/argo-ghcr-code
        manifest-repo: bf-luca/argo-ghcr-k8s
        manifest-push-user: bf-luca [bot]
        manifest-push-mail: luca.dreiling@bergfreunde.de
        PAT_GITHUB_TOKEN: ${{ secrets.PAT_GITHUB_TOKEN }}