name: Build and Push to GHCR

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/*'
      - './helloserver/*'
      - './Dockerfile-helloserver'

# Not very safe
permissions: write-all

jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
    - name: Build and test go
      uses: ./.github/workflows/composite/build-test-go
      with:
        app-path: helloserver

    - name: Upload Dockerfile
      uses: ./.github/workflows/composite/upload-dockerfile-ghcr
      with:
        dockerhub-repo: bfminusluca/argo-ghcr-code
        app-path: helloserver

    - name: Set working directory
      uses: ./.github/workflows/composite/sync-manifest
      with:
        app-path: helloserver
        manifest-push-user: bf-luca [bot]
        manifest-push-mail: luca.dreiling@bergfreunde.de